sudo: false
language: node_js
node_js:
  - '6'
  - '7'
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn
  - yarn run setup
  - yarn run build
cache: yarn
script:
  - yarn test
addons:
  firefox: "46.0"
